---
ad8c3125:
  datacenter: wec
  consul_node_name: service-discovery-server-0
  branch_name: cert
  environment: prod
  unused1:
  unused2:
  unused3:
  unused4:
e530095c:
  datacenter: wec
  consul_node_name: service-discovery-server-1
  branch_name: cert
  environment: prod
  unused1:
  unused2:
  unused3:
  unused4:
e577775c:
  datacenter: oxdc
  consul_node_name: apim-ap-manager-publisher-0
  branch_name: sand
  environment: test
  unused1:
  unused2:
  unused3:
  unused4:
node_to_ignore:
  datacenter: wec
  branch_name: cert
  environment: 'prod'
  environment: prod
  server_role: 'internal'
  unused1:
  unused2:
  unused3:
  unused4:
